# WEB SCRAPPING

In [28]:
import pandas as pd
import requests 
from bs4 import BeautifulSoup
import re

In [1]:

requests.get('https://www.ambitionbox.com/list-of-companies?page=1').text

NameError: name 'requests' is not defined

# if response code is 403

In [3]:
headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page=1', headers = headers).text

In [4]:
soup = BeautifulSoup(webpage,'lxml')

In [5]:
for i in soup.find_all('h2', class_='companyCardWrapper__companyName'):
    print(i.text.strip())

TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
ICICI Bank
HCLTech
Tech Mahindra
Genpact
Teleperformance
Axis Bank
Jio
Concentrix Corporation
Amazon
iEnergizer
Reliance Retail
IBM
LTIMindtree

In [6]:
for i in soup.find_all('div', class_='rating_text'):
    print(i.text.strip())

3.4
3.7
3.6
3.7
3.7
3.8
3.5
4.0
3.4
3.4
3.6
3.8
3.6
4.3
3.6
3.9
4.6
3.9
3.9
3.6

In [7]:
for i in soup.find_all('span', class_='companyCardWrapper__companyRatingCount'):
    print(i.text.strip())

(1.1L)
(70.1k)
(62.3k)
(59.3k)
(50.9k)
(49.6k)
(46.6k)
(44.7k)
(43.8k)
(41.8k)
(40.1k)
(36k)
(31.8k)
(31.2k)
(31.1k)
(30.3k)
(27.4k)
(26.6k)
(25.1k)
(24.8k)

In [8]:
# main code starts from here

In [9]:
company = soup.find_all('div', class_ = 'companyCardWrapper')

In [10]:
len(company)

20

In [11]:
company[0].find_all('span', class_='companyCardWrapper__ratingValues')[0].text.strip()

'Job Security'

In [79]:
action = company[0].find_all('a', class_='companyCardWrapper__ActionWrapper')

In [19]:
name=[]
rating=[]
review=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
highly_rated_for=[]
critically_rated_for=[]
company_type=[]
locations=[]
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_='rating_text').text.strip())
    text = i.find('span', class_='companyCardWrapper__interLinking').text.strip()
    before,after = text.split('|', 1)
    before=before.strip()
    company_type.append(before)
    rating_values_element = i.find_all('span', class_='companyCardWrapper__ratingValues')
    if len(rating_values_element) > 0:
        highly_rated_for.append(rating_values_element[0].text.strip())
    else:
        highly_rated_for.append(None)
    if len(rating_values_element) > 1:
        critically_rated_for.append(rating_values_element[1].text.strip())
    else:
        critically_rated_for.append(None)
    action = i.find_all('a', class_='companyCardWrapper__ActionWrapper')
    review.append(action[0].text.strip())
    salaries.append(action[1].text.strip())
    interviews.append(action[2].text.strip())
    jobs.append(action[3].text.strip())
    benefits.append(action[4].text.strip())
    
#d = {'name':name,'rating':rating,'company_type':company_type,'highly_rated_for':highly_rated_for,'critically_rated_for':critically_rated_for,'review':review,'salaries':salaries,'interviews':interviews,'jobs':jobs,'benefits':benefits}
#df = pd.DataFrame(d)
#df

In [25]:
name=[]
rating=[]
review=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
highly_rated_for=[]
critically_rated_for=[]
company_type=[]
locations=[]

for i in company:

    # --- NAME ---
    h2 = i.find('h2')
    name.append(h2.text.strip() if h2 else None)

    # --- RATING ---
    r = i.find('div', class_='rating_text')
    rating.append(r.text.strip() if r else None)

    # --- COMPANY TYPE ---
    span = i.find('span', class_='companyCardWrapper__interLinking')
    if span:
        text = span.text.strip()
        before, after = text.split('|', 1)
        company_type.append(before.strip())
    else:
        company_type.append(None)

    # --- HIGHLY & CRITICALLY RATED FOR ---
    rating_values_element = i.find_all('span', class_='companyCardWrapper__ratingValues')

    highly_rated_for.append(
        rating_values_element[0].text.strip() if len(rating_values_element) > 0 else None
    )

    critically_rated_for.append(
        rating_values_element[1].text.strip() if len(rating_values_element) > 1 else None
    )

    # --- ACTION BUTTONS ---
    action = i.find_all('a', class_='companyCardWrapper__ActionWrapper')

    review.append(action[0].text.strip() if len(action) > 0 else None)
    salaries.append(action[1].text.strip() if len(action) > 1 else None)
    interviews.append(action[2].text.strip() if len(action) > 2 else None)
    jobs.append(action[3].text.strip() if len(action) > 3 else None)
    benefits.append(action[4].text.strip() if len(action) > 4 else None)


d = {'name':name,'rating':rating,'company_type':company_type,'highly_rated_for':highly_rated_for,'critically_rated_for':critically_rated_for,'review':review,'salaries':salaries,'interviews':interviews,'jobs':jobs,'benefits':benefits}
df = pd.DataFrame(d)
df

,name,rating,company_type,highly_rated_for,critically_rated_for,review,salaries,interviews,jobs,benefits
0,TCS,3.4,IT Services & Consulting,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",1.1L Reviews,9.6L Salaries,11.7k Interviews,2.4k Jobs,10.6k Benefits
1,Accenture,3.7,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,70.1k Reviews,6.4L Salaries,9k Interviews,36.1k Jobs,6.7k Benefits
2,Wipro,3.6,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,62.3k Reviews,4.7L Salaries,6.5k Interviews,6.4k Jobs,4.6k Benefits
3,Cognizant,3.7,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,59.3k Reviews,5.9L Salaries,6.2k Interviews,840 Jobs,5.5k Benefits
4,Capgemini,3.7,IT Services & Consulting,"Work Life Balance, Job Security","Promotions / Appraisal, Salary & Benefits, Wor...",50.9k Reviews,4.7L Salaries,5.3k Interviews,2.1k Jobs,3.6k Benefits
5,HDFC Bank,3.8,Banking,"Job Security, Skill Development / Learning",Promotions / Appraisal,49.6k Reviews,1.5L Salaries,2.8k Interviews,214 Jobs,3.2k Benefits
6,Infosys,3.5,IT Services & Consulting,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",46.6k Reviews,5.1L Salaries,8.2k Interviews,3k Jobs,4.8k Benefits
7,ICICI Bank,4.0,Banking,"Job Security, Company Culture, Promotions / Ap...",None,44.7k Reviews,1.5L Salaries,2.8k Interviews,31 Jobs,3.7k Benefits
8,HCLTech,3.4,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,43.8k Reviews,3.7L Salaries,4.4k Interviews,310 Jobs,3.8k Benefits
9,Tech Mahindra,3.4,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,41.8k Reviews,2.8L Salaries,4.4k Interviews,462 Jobs,3.4k Benefits
10,Genpact,3.6,IT Services & Consulting,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",40.1k Reviews,2.3L Salaries,3.7k Interviews,296 Jobs,3.5k Benefits
11,Teleperformance,3.8,BPO,None,None,36k Reviews,95.1k Salaries,2.1k Interviews,1.3k Jobs,1.8k Benefits
12,Axis Bank,3.6,Banking,"Promotions / Appraisal, Work Satisfaction, Com...",None,31.8k Reviews,1L Salaries,1.8k Interviews,243 Jobs,2.1k Benefits
13,Jio,4.3,Telecom,"Job Security, Skill Development / Learning, Co...",None,31.2k Reviews,62.3k Salaries,3.4k Interviews,3 Jobs,2.5k Benefits
14,Concentrix Corporation,3.6,BPO,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",31.1k Reviews,1.3L Salaries,1.9k Interviews,75 Jobs,3.1k Benefits
15,Amazon,3.9,Internet,"Company Culture, Work Life Balance, Salary & B...",Promotions / Appraisal,30.3k Reviews,1.4L Salaries,5.7k Interviews,1.4k Jobs,4.1k Benefits
16,iEnergizer,4.6,BPO,"Company Culture, Work Life Balance, Work Satis...",None,27.4k Reviews,23.8k Salaries,965 Interviews,51 Jobs,430 Benefits
17,Reliance Retail,3.9,Retail,"Skill Development / Learning, Work Life Balanc...",Promotions / Appraisal,26.6k Reviews,74.2k Salaries,1.9k Interviews,21 Jobs,1.9k Benefits
18,IBM,3.9,IT Services & Consulting,"Work Life Balance, Company Culture, Job Security",Promotions / Appraisal,25.1k Reviews,2.1L Salaries,2.6k Interviews,3k Jobs,2.6k Benefits
19,LTIMindtree,3.6,IT Services & Consulting,"Promotions / Appraisal, Salary & Benefits, Wor...",None,24.8k Reviews,1.9L Salaries,3.2k Interviews,483 Jobs,775 Benefits

In [32]:


def keep_number_unit(text):
    if text is None:
        return None
    
    match = re.search(r'[\d.]+\s*[kL]', text)
    return match.group().replace(" ", "") if match else None

In [29]:
name=[]
rating=[]
review=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
highly_rated_for=[]
critically_rated_for=[]

industry=[]
headquarter=[]
other_locations_count=[]

In [30]:
import re

for i in company:

    # --- NAME ---
    h2 = i.find('h2')
    name.append(h2.text.strip() if h2 else None)

    # --- RATING ---
    r = i.find('div', class_='rating_text')
    rating.append(r.text.strip() if r else None)

    # --- INDUSTRY | HEADQUARTER | OTHER LOCATIONS ---
    span = i.find('span', class_='companyCardWrapper__interLinking')
    
    if span:
        text = span.text.strip()

        parts = text.split('|')
        industry.append(parts[0].strip())

        location_part = parts[1].strip() if len(parts) > 1 else None

        if location_part:
            # HQ
            hq = re.search(r'^[A-Za-z /]+', location_part)
            headquarter.append(hq.group().strip() if hq else None)

            # Other locations count
            count = re.search(r'\+(\d+)', location_part)
            other_locations_count.append(int(count.group(1)) if count else 0)
        else:
            headquarter.append(None)
            other_locations_count.append(0)
    else:
        industry.append(None)
        headquarter.append(None)
        other_locations_count.append(0)

    # --- HIGHLY & CRITICALLY RATED FOR ---
    rating_values_element = i.find_all('span', class_='companyCardWrapper__ratingValues')

    highly_rated_for.append(
        rating_values_element[0].text.strip() if len(rating_values_element) > 0 else None
    )

    critically_rated_for.append(
        rating_values_element[1].text.strip() if len(rating_values_element) > 1 else None
    )

    # --- ACTION BUTTONS ---
    action = i.find_all('a', class_='companyCardWrapper__ActionWrapper')

    review.append(action[0].text.strip() if len(action) > 0 else None)
    salaries.append(action[1].text.strip() if len(action) > 1 else None)
    interviews.append(action[2].text.strip() if len(action) > 2 else None)
    jobs.append(action[3].text.strip() if len(action) > 3 else None)
    benefits.append(action[4].text.strip() if len(action) > 4 else None)

In [31]:
d = {
    'name': name,
    'rating': rating,
    'industry': industry,
    'headquarter': headquarter,
    'other_locations': other_locations_count,
    'highly_rated_for': highly_rated_for,
    'critically_rated_for': critically_rated_for,
    'review': review,
    'salaries': salaries,
    'interviews': interviews,
    'jobs': jobs,
    'benefits': benefits
}

df = pd.DataFrame(d)
df

,name,rating,industry,headquarter,other_locations,highly_rated_for,critically_rated_for,review,salaries,interviews,jobs,benefits
0,TCS,3.4,IT Services & Consulting,Bangalore / Bengaluru,436,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",1.1L Reviews,9.6L Salaries,11.7k Interviews,2.4k Jobs,10.6k Benefits
1,Accenture,3.7,IT Services & Consulting,Bangalore / Bengaluru,250,"Promotions / Appraisal, Salary & Benefits, Wor...",None,70.1k Reviews,6.4L Salaries,9k Interviews,36.1k Jobs,6.7k Benefits
2,Wipro,3.6,IT Services & Consulting,Hyderabad / Secunderabad,369,"Promotions / Appraisal, Salary & Benefits, Wor...",None,62.3k Reviews,4.7L Salaries,6.5k Interviews,6.4k Jobs,4.6k Benefits
3,Cognizant,3.7,IT Services & Consulting,Hyderabad / Secunderabad,230,"Promotions / Appraisal, Salary & Benefits, Wor...",None,59.3k Reviews,5.9L Salaries,6.2k Interviews,840 Jobs,5.5k Benefits
4,Capgemini,3.7,IT Services & Consulting,Bangalore / Bengaluru,183,"Work Life Balance, Job Security","Promotions / Appraisal, Salary & Benefits, Wor...",50.9k Reviews,4.7L Salaries,5.3k Interviews,2.1k Jobs,3.6k Benefits
5,HDFC Bank,3.8,Banking,Mumbai,1806,"Job Security, Skill Development / Learning",Promotions / Appraisal,49.6k Reviews,1.5L Salaries,2.8k Interviews,214 Jobs,3.2k Benefits
6,Infosys,3.5,IT Services & Consulting,Bangalore / Bengaluru,244,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",46.6k Reviews,5.1L Salaries,8.2k Interviews,3k Jobs,4.8k Benefits
7,ICICI Bank,4.0,Banking,Mumbai,1433,"Job Security, Company Culture, Promotions / Ap...",None,44.7k Reviews,1.5L Salaries,2.8k Interviews,31 Jobs,3.7k Benefits
8,HCLTech,3.4,IT Services & Consulting,Chennai,227,"Promotions / Appraisal, Salary & Benefits, Wor...",None,43.8k Reviews,3.7L Salaries,4.4k Interviews,310 Jobs,3.8k Benefits
9,Tech Mahindra,3.4,IT Services & Consulting,Hyderabad / Secunderabad,333,"Promotions / Appraisal, Salary & Benefits, Wor...",None,41.8k Reviews,2.8L Salaries,4.4k Interviews,462 Jobs,3.4k Benefits
10,Genpact,3.6,IT Services & Consulting,Hyderabad / Secunderabad,182,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",40.1k Reviews,2.3L Salaries,3.7k Interviews,296 Jobs,3.5k Benefits
11,Teleperformance,3.8,BPO,Mumbai,252,None,None,36k Reviews,95.1k Salaries,2.1k Interviews,1.3k Jobs,1.8k Benefits
12,Axis Bank,3.6,Banking,Mumbai,1490,"Promotions / Appraisal, Work Satisfaction, Com...",None,31.8k Reviews,1L Salaries,1.8k Interviews,243 Jobs,2.1k Benefits
13,Jio,4.3,Telecom,Mumbai,1851,"Job Security, Skill Development / Learning, Co...",None,31.2k Reviews,62.3k Salaries,3.4k Interviews,3 Jobs,2.5k Benefits
14,Concentrix Corporation,3.6,BPO,Bangalore / Bengaluru,175,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",31.1k Reviews,1.3L Salaries,1.9k Interviews,75 Jobs,3.1k Benefits
15,Amazon,3.9,Internet,Bangalore / Bengaluru,519,"Company Culture, Work Life Balance, Salary & B...",Promotions / Appraisal,30.3k Reviews,1.4L Salaries,5.7k Interviews,1.4k Jobs,4.1k Benefits
16,iEnergizer,4.6,BPO,Noida,51,"Company Culture, Work Life Balance, Work Satis...",None,27.4k Reviews,23.8k Salaries,965 Interviews,51 Jobs,430 Benefits
17,Reliance Retail,3.9,Retail,Mumbai,1140,"Skill Development / Learning, Work Life Balanc...",Promotions / Appraisal,26.6k Reviews,74.2k Salaries,1.9k Interviews,21 Jobs,1.9k Benefits
18,IBM,3.9,IT Services & Consulting,Bangalore / Bengaluru,160,"Work Life Balance, Company Culture, Job Security",Promotions / Appraisal,25.1k Reviews,2.1L Salaries,2.6k Interviews,3k Jobs,2.6k Benefits
19,LTIMindtree,3.6,IT Services & Consulting,Bangalore / Bengaluru,144,"Promotions / Appraisal, Salary & Benefits, Wor...",None,24.8k Reviews,1.9L Salaries,3.2k Interviews,483 Jobs,775 Benefits

In [34]:
df['reviews'] = df['review'].apply(keep_number_unit)
df['salaries'] = df['salaries'].apply(keep_number_unit)
df['interviews'] = df['interviews'].apply(keep_number_unit)
df['jobs'] = df['jobs'].apply(keep_number_unit)
df['benefits'] = df['benefits'].apply(keep_number_unit)

In [35]:
df

,name,rating,industry,headquarter,other_locations,highly_rated_for,critically_rated_for,review,salaries,interviews,jobs,benefits,reviews
0,TCS,3.4,IT Services & Consulting,Bangalore / Bengaluru,436,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",1.1L Reviews,9.6L,11.7k,2.4k,10.6k,1.1L
1,Accenture,3.7,IT Services & Consulting,Bangalore / Bengaluru,250,"Promotions / Appraisal, Salary & Benefits, Wor...",None,70.1k Reviews,6.4L,9k,36.1k,6.7k,70.1k
2,Wipro,3.6,IT Services & Consulting,Hyderabad / Secunderabad,369,"Promotions / Appraisal, Salary & Benefits, Wor...",None,62.3k Reviews,4.7L,6.5k,6.4k,4.6k,62.3k
3,Cognizant,3.7,IT Services & Consulting,Hyderabad / Secunderabad,230,"Promotions / Appraisal, Salary & Benefits, Wor...",None,59.3k Reviews,5.9L,6.2k,None,5.5k,59.3k
4,Capgemini,3.7,IT Services & Consulting,Bangalore / Bengaluru,183,"Work Life Balance, Job Security","Promotions / Appraisal, Salary & Benefits, Wor...",50.9k Reviews,4.7L,5.3k,2.1k,3.6k,50.9k
5,HDFC Bank,3.8,Banking,Mumbai,1806,"Job Security, Skill Development / Learning",Promotions / Appraisal,49.6k Reviews,1.5L,2.8k,None,3.2k,49.6k
6,Infosys,3.5,IT Services & Consulting,Bangalore / Bengaluru,244,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",46.6k Reviews,5.1L,8.2k,3k,4.8k,46.6k
7,ICICI Bank,4.0,Banking,Mumbai,1433,"Job Security, Company Culture, Promotions / Ap...",None,44.7k Reviews,1.5L,2.8k,None,3.7k,44.7k
8,HCLTech,3.4,IT Services & Consulting,Chennai,227,"Promotions / Appraisal, Salary & Benefits, Wor...",None,43.8k Reviews,3.7L,4.4k,None,3.8k,43.8k
9,Tech Mahindra,3.4,IT Services & Consulting,Hyderabad / Secunderabad,333,"Promotions / Appraisal, Salary & Benefits, Wor...",None,41.8k Reviews,2.8L,4.4k,None,3.4k,41.8k
10,Genpact,3.6,IT Services & Consulting,Hyderabad / Secunderabad,182,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",40.1k Reviews,2.3L,3.7k,None,3.5k,40.1k
11,Teleperformance,3.8,BPO,Mumbai,252,None,None,36k Reviews,95.1k,2.1k,1.3k,1.8k,36k
12,Axis Bank,3.6,Banking,Mumbai,1490,"Promotions / Appraisal, Work Satisfaction, Com...",None,31.8k Reviews,1L,1.8k,None,2.1k,31.8k
13,Jio,4.3,Telecom,Mumbai,1851,"Job Security, Skill Development / Learning, Co...",None,31.2k Reviews,62.3k,3.4k,None,2.5k,31.2k
14,Concentrix Corporation,3.6,BPO,Bangalore / Bengaluru,175,Job Security,"Promotions / Appraisal, Salary & Benefits, Wor...",31.1k Reviews,1.3L,1.9k,None,3.1k,31.1k
15,Amazon,3.9,Internet,Bangalore / Bengaluru,519,"Company Culture, Work Life Balance, Salary & B...",Promotions / Appraisal,30.3k Reviews,1.4L,5.7k,1.4k,4.1k,30.3k
16,iEnergizer,4.6,BPO,Noida,51,"Company Culture, Work Life Balance, Work Satis...",None,27.4k Reviews,23.8k,None,None,None,27.4k
17,Reliance Retail,3.9,Retail,Mumbai,1140,"Skill Development / Learning, Work Life Balanc...",Promotions / Appraisal,26.6k Reviews,74.2k,1.9k,None,1.9k,26.6k
18,IBM,3.9,IT Services & Consulting,Bangalore / Bengaluru,160,"Work Life Balance, Company Culture, Job Security",Promotions / Appraisal,25.1k Reviews,2.1L,2.6k,3k,2.6k,25.1k
19,LTIMindtree,3.6,IT Services & Consulting,Bangalore / Bengaluru,144,"Promotions / Appraisal, Salary & Benefits, Wor...",None,24.8k Reviews,1.9L,3.2k,None,None,24.8k

In [ ]:
final = pd.DataFrame()

for j in range(1,11):
    headers={'User-Agent':'Mozilla/5.0 (Windows NT 6.3; Win 64 ; x64) Apple WeKit /537.36(KHTML , like Gecko) Chrome/80.0.3987.162 Safari/537.36'}
    webpage = requests.get('https://www.ambitionbox.com/list-of-companies?page={}'.format(j), headers = headers).text
    company = soup.find_all('div', class_ = 'companyCardWrapper')
    name=[]
rating=[]
review=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
highly_rated_for=[]
critically_rated_for=[]
company_type=[]
locations=[]
for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find('div',class_='rating_text').text.strip())
    text = i.find('span', class_='companyCardWrapper__interLinking').text.strip()
    before,after = text.split('|', 1)
    before=before.strip()
    company_type.append(before)
    rating_values_element = i.find_all('span', class_='companyCardWrapper__ratingValues')
    if len(rating_values_element) > 0:
        highly_rated_for.append(rating_values_element[0].text.strip())
    else:
        highly_rated_for.append(None)
    if len(rating_values_element) > 1:
        critically_rated_for.append(rating_values_element[1].text.strip())
    else:
        critically_rated_for.append(None)
    action = i.find_all('a', class_='companyCardWrapper__ActionWrapper')
    review.append(action[0])
    salaries.append(action[1])
    interviews.append(action[2])
    jobs.append(action[3])
    benefits.append(action[4])
    
d = {'name':name,'rating':rating,'company_type':company_type,'highly_rated_for':highly_rated_for,'critically_rated_for':critically_rated_for,'action':action,'review':review,'salaries':salaries,'interviews':interviews,'jobs':jobs,'benefits':benefits}
df = pd.DataFrame(d)
final = final.append(df, ignore_index=True)

# FINAL CODE

In [1]:
import re
import time
import requests
from bs4 import BeautifulSoup

name=[]
rating=[]
reviews=[]
salaries=[]
interviews=[]
jobs=[]
benefits=[]
highly_rated_for=[]
critically_rated_for=[]
industry=[]
headquarter=[]
other_locations_count=[]

headers = {
    'User-Agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36'
}

for j in range(1, 501):

    print(f"Scraping page {j}...")

    url = f'https://www.ambitionbox.com/list-of-companies?page={j}'
    response = requests.get(url, headers=headers, timeout=10)

    if response.status_code != 200:
        print(f"⚠️ Page {j} failed")
        continue

    soup = BeautifulSoup(response.text, 'html.parser')
    companies = soup.find_all('div', class_='companyCardWrapper')

    for i in companies:

        # ---------- NAME ----------
        h2 = i.find('h2')
        name.append(h2.text.strip() if h2 else None)

        # ---------- RATING ----------
        r = i.find('div', class_='rating_text')
        rating.append(r.text.strip() if r else None)

        # ---------- INDUSTRY | HQ | LOCATIONS ----------
        span = i.find('span', class_='companyCardWrapper__interLinking')

        if span:
            text = span.text.strip()
            parts = text.split('|')

            industry.append(parts[0].strip())

            location_part = parts[1].strip() if len(parts) > 1 else None

            if location_part:
                hq = re.search(r'^[A-Za-z /]+', location_part)
                headquarter.append(hq.group().strip() if hq else None)

                count = re.search(r'\+(\d+)', location_part)
                other_locations_count.append(int(count.group(1)) if count else 0)
            else:
                headquarter.append(None)
                other_locations_count.append(0)
        else:
            industry.append(None)
            headquarter.append(None)
            other_locations_count.append(0)

        # ---------- HIGHLY / CRITICALLY RATED ----------
        rating_values = i.find_all('span', class_='companyCardWrapper__ratingValues')

        highly_rated_for.append(
            rating_values[0].text.strip() if len(rating_values) > 0 else None
        )

        critically_rated_for.append(
            rating_values[1].text.strip() if len(rating_values) > 1 else None
        )

        # ---------- ACTION BUTTONS (FIXED) ----------
        action_dict = {
            'Reviews': None,
            'Salaries': None,
            'Interviews': None,
            'Jobs': None,
            'Benefits': None
        }

        actions = i.find_all('a', class_='companyCardWrapper__ActionWrapper')

        for a in actions:
            title = a.find('span', class_='companyCardWrapper__ActionTitle')
            count = a.find('span', class_='companyCardWrapper__ActionCount')

            if title and count:
                key = title.text.strip()
                if key in action_dict:
                    action_dict[key] = count.text.strip()

        reviews.append(action_dict['Reviews'])
        salaries.append(action_dict['Salaries'])
        interviews.append(action_dict['Interviews'])
        jobs.append(action_dict['Jobs'])
        benefits.append(action_dict['Benefits'])

    # 🔒 Delay to avoid blocking
    time.sleep(1)

Scraping page 1...
Scraping page 2...
Scraping page 3...
Scraping page 4...
Scraping page 5...
Scraping page 6...
Scraping page 7...
Scraping page 8...
Scraping page 9...
Scraping page 10...
Scraping page 11...
Scraping page 12...
Scraping page 13...
Scraping page 14...
Scraping page 15...
Scraping page 16...
Scraping page 17...
Scraping page 18...
Scraping page 19...
Scraping page 20...
Scraping page 21...
Scraping page 22...
Scraping page 23...
Scraping page 24...
Scraping page 25...
Scraping page 26...
Scraping page 27...
Scraping page 28...
Scraping page 29...
Scraping page 30...
Scraping page 31...
Scraping page 32...
Scraping page 33...
Scraping page 34...
Scraping page 35...
Scraping page 36...
Scraping page 37...
Scraping page 38...
Scraping page 39...
Scraping page 40...
Scraping page 41...
Scraping page 42...
Scraping page 43...
Scraping page 44...
Scraping page 45...
Scraping page 46...
Scraping page 47...
Scraping page 48...
Scraping page 49...
Scraping page 50...
Scraping page 51...
Scraping page 52...
Scraping page 53...
Scraping page 54...
Scraping page 55...
Scraping page 56...
Scraping page 57...
Scraping page 58...
Scraping page 59...
Scraping page 60...
Scraping page 61...
Scraping page 62...
Scraping page 63...
Scraping page 64...
Scraping page 65...
Scraping page 66...
Scraping page 67...
Scraping page 68...
Scraping page 69...
Scraping page 70...
Scraping page 71...
Scraping page 72...
Scraping page 73...
Scraping page 74...
Scraping page 75...
Scraping page 76...
Scraping page 77...
Scraping page 78...
Scraping page 79...
Scraping page 80...
Scraping page 81...
Scraping page 82...
Scraping page 83...
Scraping page 84...
Scraping page 85...
Scraping page 86...
Scraping page 87...
Scraping page 88...
Scraping page 89...
Scraping page 90...
Scraping page 91...
Scraping page 92...
Scraping page 93...
Scraping page 94...
Scraping page 95...
Scraping page 96...
Scraping page 97...
Scraping page 98...
Scraping page 99...
Scraping page 100...
Scraping page 101...
Scraping page 102...
Scraping page 103...
Scraping page 104...
Scraping page 105...
Scraping page 106...
Scraping page 107...
Scraping page 108...
Scraping page 109...
Scraping page 110...
Scraping page 111...
Scraping page 112...
Scraping page 113...
Scraping page 114...
Scraping page 115...
Scraping page 116...
Scraping page 117...
Scraping page 118...
Scraping page 119...
Scraping page 120...
Scraping page 121...
Scraping page 122...
Scraping page 123...
Scraping page 124...
Scraping page 125...
Scraping page 126...
Scraping page 127...
Scraping page 128...
Scraping page 129...
Scraping page 130...
Scraping page 131...
Scraping page 132...
Scraping page 133...
Scraping page 134...
Scraping page 135...
Scraping page 136...
Scraping page 137...
Scraping page 138...
Scraping page 139...
Scraping page 140...
Scraping page 141...
Scraping page 142...
Scraping page 143...
Scraping page 144...
Scraping page 145...
Scraping page 146...
Scraping page 147...
Scraping page 148...
Scraping page 149...
Scraping page 150...
Scraping page 151...
Scraping page 152...
Scraping page 153...
Scraping page 154...
Scraping page 155...
Scraping page 156...
Scraping page 157...
Scraping page 158...
Scraping page 159...
Scraping page 160...
Scraping page 161...
Scraping page 162...
Scraping page 163...
Scraping page 164...
Scraping page 165...
Scraping page 166...
Scraping page 167...
Scraping page 168...
Scraping page 169...
Scraping page 170...
Scraping page 171...
Scraping page 172...
Scraping page 173...
Scraping page 174...
Scraping page 175...
Scraping page 176...
Scraping page 177...
Scraping page 178...
Scraping page 179...
Scraping page 180...
Scraping page 181...
Scraping page 182...
Scraping page 183...
Scraping page 184...
Scraping page 185...
Scraping page 186...
Scraping page 187...
Scraping page 188...
Scraping page 189...
Scraping page 190...
Scraping page 191...
Scraping page 192...
Scraping page 193...
Scraping page 194...
Scraping page 195...
Scraping page 196...
Scraping page 197...
Scraping page 198...
Scraping page 199...
Scraping page 200...
Scraping page 201...
Scraping page 202...
Scraping page 203...
Scraping page 204...
Scraping page 205...
Scraping page 206...
Scraping page 207...
Scraping page 208...
Scraping page 209...
Scraping page 210...
Scraping page 211...
Scraping page 212...
Scraping page 213...
Scraping page 214...
Scraping page 215...
Scraping page 216...
Scraping page 217...
Scraping page 218...
Scraping page 219...
Scraping page 220...
Scraping page 221...
Scraping page 222...
Scraping page 223...
Scraping page 224...
Scraping page 225...
Scraping page 226...
Scraping page 227...
Scraping page 228...
Scraping page 229...
Scraping page 230...
Scraping page 231...
Scraping page 232...
Scraping page 233...
Scraping page 234...
Scraping page 235...
Scraping page 236...
Scraping page 237...
Scraping page 238...
Scraping page 239...
Scraping page 240...
Scraping page 241...
Scraping page 242...
Scraping page 243...
Scraping page 244...
Scraping page 245...
Scraping page 246...
Scraping page 247...
Scraping page 248...
Scraping page 249...
Scraping page 250...
Scraping page 251...
Scraping page 252...
Scraping page 253...
Scraping page 254...
Scraping page 255...
Scraping page 256...
Scraping page 257...
Scraping page 258...
Scraping page 259...
Scraping page 260...
Scraping page 261...
Scraping page 262...
Scraping page 263...
Scraping page 264...
Scraping page 265...
Scraping page 266...
Scraping page 267...
Scraping page 268...
Scraping page 269...
Scraping page 270...
Scraping page 271...
Scraping page 272...
Scraping page 273...
Scraping page 274...
Scraping page 275...
Scraping page 276...
Scraping page 277...
Scraping page 278...
Scraping page 279...
Scraping page 280...
Scraping page 281...
Scraping page 282...
Scraping page 283...
Scraping page 284...
Scraping page 285...
Scraping page 286...
Scraping page 287...
Scraping page 288...
Scraping page 289...
Scraping page 290...
Scraping page 291...
Scraping page 292...
Scraping page 293...
Scraping page 294...
Scraping page 295...
Scraping page 296...
Scraping page 297...
Scraping page 298...
Scraping page 299...
Scraping page 300...
Scraping page 301...
Scraping page 302...
Scraping page 303...
Scraping page 304...
Scraping page 305...
Scraping page 306...
Scraping page 307...
Scraping page 308...
Scraping page 309...
Scraping page 310...
Scraping page 311...
Scraping page 312...
Scraping page 313...
Scraping page 314...
Scraping page 315...
Scraping page 316...
Scraping page 317...
Scraping page 318...
Scraping page 319...
Scraping page 320...
Scraping page 321...
Scraping page 322...
Scraping page 323...
Scraping page 324...
Scraping page 325...
Scraping page 326...
Scraping page 327...
Scraping page 328...
Scraping page 329...
Scraping page 330...
Scraping page 331...
Scraping page 332...
Scraping page 333...
Scraping page 334...
Scraping page 335...
Scraping page 336...
Scraping page 337...
Scraping page 338...
Scraping page 339...
Scraping page 340...
Scraping page 341...
Scraping page 342...
Scraping page 343...
Scraping page 344...
Scraping page 345...
Scraping page 346...
Scraping page 347...
Scraping page 348...
Scraping page 349...
Scraping page 350...
Scraping page 351...
Scraping page 352...
Scraping page 353...
Scraping page 354...
Scraping page 355...
Scraping page 356...
Scraping page 357...
Scraping page 358...
Scraping page 359...
Scraping page 360...
Scraping page 361...
Scraping page 362...
Scraping page 363...
Scraping page 364...
Scraping page 365...
Scraping page 366...
Scraping page 367...
Scraping page 368...
Scraping page 369...
Scraping page 370...
Scraping page 371...
Scraping page 372...
Scraping page 373...
Scraping page 374...
Scraping page 375...
Scraping page 376...
Scraping page 377...
Scraping page 378...
Scraping page 379...
Scraping page 380...
Scraping page 381...
Scraping page 382...
Scraping page 383...
Scraping page 384...
Scraping page 385...
Scraping page 386...
Scraping page 387...
Scraping page 388...
Scraping page 389...
Scraping page 390...
Scraping page 391...
Scraping page 392...
Scraping page 393...
Scraping page 394...
Scraping page 395...
Scraping page 396...
Scraping page 397...
Scraping page 398...
Scraping page 399...
Scraping page 400...
Scraping page 401...
Scraping page 402...
Scraping page 403...
Scraping page 404...
Scraping page 405...
Scraping page 406...
Scraping page 407...
Scraping page 408...
Scraping page 409...
Scraping page 410...
Scraping page 411...
Scraping page 412...
Scraping page 413...
Scraping page 414...
Scraping page 415...
Scraping page 416...
Scraping page 417...
Scraping page 418...
Scraping page 419...
Scraping page 420...
Scraping page 421...
Scraping page 422...
Scraping page 423...
Scraping page 424...
Scraping page 425...
Scraping page 426...
Scraping page 427...
Scraping page 428...
Scraping page 429...
Scraping page 430...
Scraping page 431...
Scraping page 432...
Scraping page 433...
Scraping page 434...
Scraping page 435...
Scraping page 436...
Scraping page 437...
Scraping page 438...
Scraping page 439...
Scraping page 440...
Scraping page 441...
Scraping page 442...
Scraping page 443...
Scraping page 444...
Scraping page 445...
Scraping page 446...
Scraping page 447...
Scraping page 448...
Scraping page 449...
Scraping page 450...
Scraping page 451...
Scraping page 452...
Scraping page 453...
Scraping page 454...
Scraping page 455...
Scraping page 456...
Scraping page 457...
Scraping page 458...
Scraping page 459...
Scraping page 460...
Scraping page 461...
Scraping page 462...
Scraping page 463...
Scraping page 464...
Scraping page 465...
Scraping page 466...
Scraping page 467...
Scraping page 468...
Scraping page 469...
Scraping page 470...
Scraping page 471...
Scraping page 472...
Scraping page 473...
Scraping page 474...
Scraping page 475...
Scraping page 476...
Scraping page 477...
Scraping page 478...
Scraping page 479...
Scraping page 480...
Scraping page 481...
Scraping page 482...
Scraping page 483...
Scraping page 484...
Scraping page 485...
Scraping page 486...
Scraping page 487...
Scraping page 488...
Scraping page 489...
Scraping page 490...
Scraping page 491...
Scraping page 492...
Scraping page 493...
Scraping page 494...
Scraping page 495...
Scraping page 496...
Scraping page 497...
Scraping page 498...
Scraping page 499...
Scraping page 500...

In [2]:
import pandas as pd

df = pd.DataFrame({
    'name': name,
    'rating': rating,
    'industry': industry,
    'headquarter': headquarter,
    'other_locations': other_locations_count,
    'highly_rated_for': highly_rated_for,
    'critically_rated_for': critically_rated_for,
    'reviews': reviews,
    'salaries': salaries,
    'interviews': interviews,
    'jobs': jobs,
    'benefits': benefits
})

df.isna().sum()

name                       0
rating                     0
industry                   0
headquarter              515
other_locations            0
highly_rated_for          30
critically_rated_for    6412
reviews                    0
salaries                   0
interviews                 0
jobs                       0
benefits                   0
dtype: int64

In [42]:
df['reviews'] = df['review'].apply(keep_number_unit)
df['salaries'] = df['salaries'].apply(keep_number_unit)
df['interviews'] = df['interviews'].apply(keep_number_unit)
df['jobs'] = df['jobs'].apply(keep_number_unit)
df['benefits'] = df['benefits'].apply(keep_number_unit)

In [47]:
df.to_csv('indian_companies_dataset1.csv')

In [3]:
df.to_csv('indian_companies_dataset.csv')